name: daily-cron
on:
  schedule:
  - cron: '05 4,9,12,15,19 * * *'

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
    - name: Update USD currency
      run: |
            curl --request POST \
            --url 'https://business-box.vercel.app/api/currency/update'