name: daily-cron
on:
  workflow_dispatch:
  schedule:
  - cron: '05 4,9,12,15,19 * * *'

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
    - name: Update USD currency
      run: |
            curl --request POST \
            --url 'https://bissbox.com/api/currency/update'
    - name: Check all liqpay Analysis orders
      run: |
            curl --request POST \
            --url 'https://bissbox.com/api/analysis/check-liqpay-all'
    - name: Check all liqpay ToTop orders
      run: |
            curl --request POST \
            --url 'https://bissbox.com/api/toporders/check-liqpay-all'
